AllCops:
  TargetRubyVersion: '2.5.0'
  Exclude:
    - test/dummy/**/*

Bundler/OrderedGems:
  Exclude:
    - Gemfile
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Max: 18
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
