# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'yard'

require 'rubocop/rake_task'
RuboCop::RakeTask.new

Rake::TestTask.new :test do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.libs << '../../api/lib'
  t.libs << '../../sdk/lib'
  t.test_files = FileList['test/**/*_test.rb']
end

YARD::Rake::YardocTask.new do |t|
  t.stats_options = ['--list-undoc']
end

if RUBY_ENGINE == 'truffleruby'
  task default: %i[test]
else
  task default: %i[test rubocop yard]
end

PROTO_VERSION = 'v0.20.0'

task :clean_protobuf do
  FileUtils.rm_rf('lib/opentelemetry/proto/*')
  FileUtils.rm_rf('opentelemetry-proto')
end

task update_protobuf: [:clean_protobuf] do
  sh("git clone -b #{PROTO_VERSION} https://github.com/open-telemetry/opentelemetry-proto")
  Dir['opentelemetry-proto/opentelemetry/proto/**/*.proto'].each do |file|
    sh('protoc', '--ruby_out=lib/', '--proto_path=opentelemetry-proto', file)
  end
  FileUtils.rm_rf('opentelemetry-proto')
end
