AllCops:
  TargetRubyVersion: "2.6.0"

Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Exclude:
    - 'lib/opentelemetry/sdk/configurator.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/opentelemetry/sdk/configurator.rb'
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 21
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-sdk.rb"
Style/ModuleFunction:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
